### ISSUE TITLE
请问学习深度学习从哪里入手比较好呢

### ISSUE THREAD

**Issue by dark-wind** [guoquan/guoquan.github.io#1]
请问深度学习从哪里入手开始学习比较好呢，只大略了解了简单的决策树、神经网络和聚类算法。
总觉得学的很散乱，没有框架和体系。。。叨扰了

**Comment by guoquan** [comment]
> 请问深度学习从哪里入手开始学习比较好呢，只大略了解了简单的决策树、神经网络和聚类算法。
> 总觉得学的很散乱，没有框架和体系。。。叨扰了

没想到会收到这一的issue呀。我假设你的目标是系统的学习“深度学习”，而非应用于开发一两个好玩的应用 ~（如果是这样，那么请参考[TensorFlow官方教程](https://www.tensorflow.org/tutorials/)，跟着例子走一遍就能做很多事情了）~ 。这个领域正在迅猛发展，很难指出一个完整的学习路径。如果只是从哪里开始，那就很清晰了： **打基础** 。

首先要明白深度学习的位置：它是机器学习的一类方法，主要以神经网络为实现形式。

你提到已经散乱的了解了一些机器学习的方法，包括神经网络，这些是很重要的基础，但是仍需要成体系的了解。首先系统的学习机器学习。对机器学习有较好的基础后就可以 *选择* 进一步学习神经网络基础（是的，这是一个选择，神经网络并不是唯一）。当这些基础都具备，就尽情的享受阅读最新的研究成果，参与科学讨论，贡献你的最新研究！

对于参考资料的选择，如果想要成体系的学习，尤其是基础阶段，千万不要选择科普材料，不要依赖科普媒体的推荐。科普和专业学习目标不同，依赖于科普学习难于形成体系。想清楚自己的目标。

- [《Deep Learning》](https://www.deeplearningbook.org/)是一个比较好的参考，尤其是第一部分，围绕机器学习给你打下基础。后两部分适合具有一些基础后再有选择的阅读。

- 中文的材料如[“西瓜书”](http://cs.nju.edu.cn/zhouzh/zhouzh.files/publication/MLbook2016.htm)也是非常好的，遗憾其中神经网络的部分较简略，不符合你目前设定的学习目标。

- 此外，我的导师译著神经网络经典教材[《神经网络设计（原书第2版）》](https://book.douban.com/subject/30236893/)也是神经网络进阶学习的绝佳选择。直到现在它仍然像一个宝藏，告诉学习者许多当前研究的根源，启发新的研究思路。

希望对你有所帮助。

**Comment by dark-wind** [comment]
谢答O(∩_∩)O

博主的定位非常清晰，这正是我想要的。

当前我学习的材料是： https://github.com/Avik-Jain/100-Days-Of-ML-Code

神经网络的发展近年是人工智能的一个重大突破方向。。当然说人工智能范围太大了。神经网络也只能解决一小部分问题。

但是面对种类繁多的机器学习理论和方法，我们不可能面面俱到，只能在一个极小的方向上深入，这也是我现在想做的，但是我并没有科研的经历和做相关工作的朋友。不知道自己是否能适应学术研究。

当然。。。考研也是硬指标

最后，感谢如此详细的解答，这个走心的回答，我觉得您一定是一位严谨的学者，博学的老师。如有机会想向您当面请教
